spring:
  application:
    name: sandemail
  spring:
    kafka:
      bootstrap-servers: kafka-broker1:9092,kafka-broker2:9092,kafka-broker3:9092
      consumer:
        group-id: email-service
        auto-offset-reset: earliest
        properties:
          spring.json.trusted.packages: "*"
    admin:
      auto-create: false
      properties:
        request.timeout.ms: 30000
        retries: 3
  pool:
    initial-size: 5
    max-size: 20
app:
  subject: "email di chi invia"
  activation:
    register-topic: "user-registered"

  main:
    web-application-type: reactive
