spring:
  application:
    name: employee
  flyway:
    enabled: true
    locations: classpath:db/migration

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20

  main:
    web-application-type: reactive

services:
  base:
    url: ${BASE_URL}
  department:
    uri: "/department/{id}"
  projects:
    uri: "/project/active/batch"
  project:
    uri: "/project/{id}"
