spring:
  application:
    name: employee
  flyway:
    enabled: true
    locations: classpath:db
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  pool:
    initial-size: 5
    max-size: 20

  main:
    web-application-type: reactive
