spring:
  application:
    name: employee
  kafka:
    bootstrap-servers: kafka-broker1:9092,kafka-broker2:9092,kafka-broker3:9092
    producer:
      acks: all
      retries: 3
      max-in-flight-requests-per-connection: 5
      delivery-timeout-ms: 120000
    admin:
      auto-create: false
      properties:
        request.timeout.ms: 30000
        retries: 3
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  pool:
    initial-size: 5
    max-size: 20

app:
  activation:
    register-link: "https://tuosito.com/activate/"
    register-topic: "user-registered"

  main:
    web-application-type: reactive
